import { TIPTAP_NODE_TYPES } from './tiptap-node-types';

// Email-only containers, buttons and raw HTML are not allowed in record rich
// text: API clients can write any node, so the server enforces this list.
export const RECORD_RICH_TEXT_NODE_TYPES: string[] = [
  TIPTAP_NODE_TYPES.DOCUMENT,
  TIPTAP_NODE_TYPES.PARAGRAPH,
  TIPTAP_NODE_TYPES.TEXT,
  TIPTAP_NODE_TYPES.HEADING,
  TIPTAP_NODE_TYPES.HARD_BREAK,
  TIPTAP_NODE_TYPES.BULLET_LIST,
  TIPTAP_NODE_TYPES.ORDERED_LIST,
  TIPTAP_NODE_TYPES.LIST_ITEM,
  TIPTAP_NODE_TYPES.TASK_LIST,
  TIPTAP_NODE_TYPES.TASK_ITEM,
  TIPTAP_NODE_TYPES.BLOCKQUOTE,
  TIPTAP_NODE_TYPES.CODE_BLOCK,
  TIPTAP_NODE_TYPES.TABLE,
  TIPTAP_NODE_TYPES.TABLE_ROW,
  TIPTAP_NODE_TYPES.TABLE_HEADER,
  TIPTAP_NODE_TYPES.TABLE_CELL,
  TIPTAP_NODE_TYPES.IMAGE,
  TIPTAP_NODE_TYPES.FILE,
  TIPTAP_NODE_TYPES.DIVIDER,
  TIPTAP_NODE_TYPES.MENTION_TAG,
  TIPTAP_NODE_TYPES.VARIABLE_TAG,
];
