export const SNOV_CLIENT_ID_VARIABLE_NAME = 'SNOV_CLIENT_ID';
export const SNOV_CLIENT_SECRET_VARIABLE_NAME = 'SNOV_CLIENT_SECRET';
export const SNOV_CREDIT_COST_DOLLARS_VARIABLE_NAME =
  'SNOV_CREDIT_COST_DOLLARS';
