import { defineIndex, STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS } from "twenty-sdk/define";
import {
  WHATSAPP_GROUP_ID_MESSAGE_THREAD_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_GROUP_ID_MESSAGE_THREAD_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_GROUP_ID_MESSAGE_THREAD_INDEX_UNIVERSAL_IDENTIFIER
} from "src/constants/universal-identifiers";

export default defineIndex({
  universalIdentifier: WHATSAPP_GROUP_ID_MESSAGE_THREAD_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.messageThread.universalIdentifier,
  isUnique: true,
  fields: [
    {
      universalIdentifier: WHATSAPP_GROUP_ID_MESSAGE_THREAD_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier: WHATSAPP_GROUP_ID_MESSAGE_THREAD_FIELD_UNIVERSAL_IDENTIFIER,
    }
  ]
})