import { type SelectOptionMeta } from 'src/types/select-option-meta';

export const JOB_DEPARTMENT_OPTIONS: readonly SelectOptionMeta[] = [
  {
    key: 'administration',
    value: 'ADMINISTRATION',
    label: 'Administration',
    color: 'blue',
    position: 0,
  },
  {
    key: 'realEstate',
    value: 'REAL_ESTATE',
    label: 'Real Estate',
    color: 'green',
    position: 1,
  },
  {
    key: 'healthcare',
    value: 'HEALTHCARE',
    label: 'Healthcare',
    color: 'purple',
    position: 2,
  },
  {
    key: 'partnerships',
    value: 'PARTNERSHIPS',
    label: 'Partnerships',
    color: 'orange',
    position: 3,
  },
  {
    key: 'cSuite',
    value: 'C_SUITE',
    label: 'C-Suite',
    color: 'sky',
    position: 4,
  },
  {
    key: 'design',
    value: 'DESIGN',
    label: 'Design',
    color: 'pink',
    position: 5,
  },
  {
    key: 'humanResources',
    value: 'HUMAN_RESOURCES',
    label: 'Human Resources',
    color: 'turquoise',
    position: 6,
  },
  {
    key: 'engineering',
    value: 'ENGINEERING',
    label: 'Engineering',
    color: 'yellow',
    position: 7,
  },
  {
    key: 'education',
    value: 'EDUCATION',
    label: 'Education',
    color: 'red',
    position: 8,
  },
  {
    key: 'strategy',
    value: 'STRATEGY',
    label: 'Strategy',
    color: 'gray',
    position: 9,
  },
  {
    key: 'product',
    value: 'PRODUCT',
    label: 'Product',
    color: 'iris',
    position: 10,
  },
  {
    key: 'sales',
    value: 'SALES',
    label: 'Sales',
    color: 'amber',
    position: 11,
  },
  { key: 'rAndD', value: 'R_D', label: 'R&D', color: 'jade', position: 12 },
  {
    key: 'retail',
    value: 'RETAIL',
    label: 'Retail',
    color: 'plum',
    position: 13,
  },
  {
    key: 'customerSuccess',
    value: 'CUSTOMER_SUCCESS',
    label: 'Customer Success',
    color: 'cyan',
    position: 14,
  },
  {
    key: 'security',
    value: 'SECURITY',
    label: 'Security',
    color: 'tomato',
    position: 15,
  },
  {
    key: 'publicService',
    value: 'PUBLIC_SERVICE',
    label: 'Public Service',
    color: 'lime',
    position: 16,
  },
  {
    key: 'creative',
    value: 'CREATIVE',
    label: 'Creative',
    color: 'violet',
    position: 17,
  },
  { key: 'it', value: 'IT', label: 'IT', color: 'bronze', position: 18 },
  {
    key: 'support',
    value: 'SUPPORT',
    label: 'Support',
    color: 'crimson',
    position: 19,
  },
  {
    key: 'marketing',
    value: 'MARKETING',
    label: 'Marketing',
    color: 'mint',
    position: 20,
  },
  { key: 'trade', value: 'TRADE', label: 'Trade', color: 'gold', position: 21 },
  { key: 'legal', value: 'LEGAL', label: 'Legal', color: 'ruby', position: 22 },
  {
    key: 'operations',
    value: 'OPERATIONS',
    label: 'Operations',
    color: 'grass',
    position: 23,
  },
  {
    key: 'procurement',
    value: 'PROCUREMENT',
    label: 'Procurement',
    color: 'brown',
    position: 24,
  },
  { key: 'data', value: 'DATA', label: 'Data', color: 'blue', position: 25 },
  {
    key: 'manufacturing',
    value: 'MANUFACTURING',
    label: 'Manufacturing',
    color: 'green',
    position: 26,
  },
  {
    key: 'logistics',
    value: 'LOGISTICS',
    label: 'Logistics',
    color: 'purple',
    position: 27,
  },
  {
    key: 'finance',
    value: 'FINANCE',
    label: 'Finance',
    color: 'orange',
    position: 28,
  },
];
