import { type SelectOptionMeta } from 'src/types/select-option-meta';

export const JOB_LEVEL_OPTIONS: readonly SelectOptionMeta[] = [
  { key: 'owner', value: 'OWNER', label: 'Owner', color: 'blue', position: 0 },
  {
    key: 'cSuite',
    value: 'C_SUITE',
    label: 'C-Suite',
    color: 'green',
    position: 1,
  },
  {
    key: 'vicePresident',
    value: 'VICE_PRESIDENT',
    label: 'Vice President',
    color: 'purple',
    position: 2,
  },
  {
    key: 'director',
    value: 'DIRECTOR',
    label: 'Director',
    color: 'orange',
    position: 3,
  },
  {
    key: 'seniorNonManagerial',
    value: 'SENIOR_NON_MANAGERIAL',
    label: 'Senior Non-Managerial',
    color: 'sky',
    position: 4,
  },
  {
    key: 'manager',
    value: 'MANAGER',
    label: 'Manager',
    color: 'pink',
    position: 5,
  },
  {
    key: 'partner',
    value: 'PARTNER',
    label: 'Partner',
    color: 'turquoise',
    position: 6,
  },
  {
    key: 'nonManagerial',
    value: 'NON_MANAGERIAL',
    label: 'Non-Managerial',
    color: 'yellow',
    position: 7,
  },
  {
    key: 'junior',
    value: 'JUNIOR',
    label: 'Junior',
    color: 'red',
    position: 8,
  },
  {
    key: 'president',
    value: 'PRESIDENT',
    label: 'President',
    color: 'gray',
    position: 9,
  },
  {
    key: 'seniorManager',
    value: 'SENIOR_MANAGER',
    label: 'Senior Manager',
    color: 'iris',
    position: 10,
  },
  {
    key: 'advisor',
    value: 'ADVISOR',
    label: 'Advisor',
    color: 'amber',
    position: 11,
  },
  {
    key: 'freelancer',
    value: 'FREELANCER',
    label: 'Freelancer',
    color: 'jade',
    position: 12,
  },
  {
    key: 'boardMember',
    value: 'BOARD_MEMBER',
    label: 'Board Member',
    color: 'plum',
    position: 13,
  },
  {
    key: 'founder',
    value: 'FOUNDER',
    label: 'Founder',
    color: 'cyan',
    position: 14,
  },
  {
    key: 'training',
    value: 'TRAINING',
    label: 'Training',
    color: 'tomato',
    position: 15,
  },
  {
    key: 'unpaid',
    value: 'UNPAID',
    label: 'Unpaid',
    color: 'lime',
    position: 16,
  },
];
