export type ZoomInfoCompanyData = {
  id?: string | number | null;
  name?: string | null;
  website?: string | null;
  socialMediaUrls?: unknown;
  street?: string | null;
  city?: string | null;
  state?: string | null;
  zipCode?: string | null;
  country?: string | null;
  metroArea?: string | null;
  continent?: string | null;
  phone?: string | null;
  description?: string | null;
  employeeCount?: number | null;
  employeeRange?: string | null;
  // Thousands of USD: a $100M company comes back as 100000.
  revenue?: number | null;
  revenueRange?: string | null;
  primaryIndustry?: unknown;
  industries?: unknown;
  sicCodes?: unknown;
  naicsCodes?: unknown;
  type?: string | null;
  companyStatus?: string | null;
  ticker?: string | null;
  foundedYear?: number | string | null;
  totalFundingAmount?: number | string | null;
  recentFundingAmount?: number | string | null;
  recentFundingDate?: string | null;
  locationCount?: number | null;
  parentName?: string | null;
  ultimateParentId?: number | string | null;
  ultimateParentName?: string | null;
  numberOfContactsInZoomInfo?: number | null;
  competitors?: unknown;
  employeeGrowth?: unknown;
  employeeCountByDepartment?: unknown;
  isDefunct?: boolean | null;
};
