export const ROCKETREACH_API_KEY_VARIABLE_NAME = 'ROCKETREACH_API_KEY';
export const REVEAL_PERSONAL_EMAIL_VARIABLE_NAME =
  'ROCKETREACH_REVEAL_PERSONAL_EMAIL';
export const REVEAL_PHONE_VARIABLE_NAME = 'ROCKETREACH_REVEAL_PHONE';
export const REVEAL_HEALTHCARE_VARIABLE_NAME =
  'ROCKETREACH_REVEAL_HEALTHCARE_ENRICHMENT';
export const LOOKUP_CONCURRENCY_VARIABLE_NAME =
  'ROCKETREACH_LOOKUP_CONCURRENCY';
export const CREDIT_COST_DOLLARS_VARIABLE_NAME =
  'ROCKETREACH_CREDIT_COST_DOLLARS';
