import { type ExploriumPersonData } from 'src/types/explorium-person-data';

export const EXPLORIUM_PERSON_DATA_MOCK: ExploriumPersonData = {
  prospect_id: 'ee936e451b50c70e068e1b54e106cb89173198c4',
  full_name: 'Jane Doe',
  first_name: 'jane',
  last_name: 'doe',
  gender: 'female',
  age_group: '35-44',
  city: 'austin',
  region_name: 'texas',
  country_name: 'united states',
  linkedin: 'https://www.linkedin.com/in/janedoe',
  linkedin_url_array: [
    'https://www.linkedin.com/in/janedoe',
    'https://www.linkedin.com/in/jane-doe-old',
  ],
  company_name: 'Acme',
  company_website: 'https://www.acme.com',
  company_linkedin: 'https://www.linkedin.com/company/acme',
  job_title: 'Head of Marketing',
  job_department_main: 'marketing',
  job_department_array: ['marketing', 'sales', 'not-a-department'],
  job_level_main: 'director',
  job_level_array: ['director'],
  experience: [{ company_name: 'Acme', title: 'Head of Marketing' }],
  education: [{ institution_name: 'UT Austin' }],
  skills: ['seo', 'branding'],
  interests: ['hiking'],
  professional_email: 'jane.doe@acme.com',
  professional_email_status: 'catch_all',
  mobile_phone: '+15125550100',
  phone_numbers: [{ phone: '+15125550100' }, { phone: '+15125550199' }],
};
