import { type FieldRichTextValue } from '@/object-record/record-field/ui/types/FieldMetadata';
import { tipTapDocumentToMarkdown } from 'twenty-shared/utils';

// Record writes get markdown regenerated by the server, but application
// variables are stored as sent, so markdown is always derived here too.
export const buildRichTextFieldValueFromTiptap = (
  tiptap: string,
): FieldRichTextValue => ({
  tiptap,
  markdown: tipTapDocumentToMarkdown(tiptap),
});
