import { type HunterCompany } from 'src/types/hunter-company';

export const HUNTER_COMPANY_DATA_MOCK: HunterCompany = {
  id: 'company-1',
  name: 'Acme Corp',
  legalName: 'Acme Corporation',
  domain: 'acme.com',
  domainAliases: ['acme.co'],
  category: {
    sector: 'Industrials',
    industry: 'Manufacturing',
    sicCode: '3499',
    naicsCode: '332999',
    gicsCode: '20106020',
  },
  tags: ['B2B'],
  description: 'Makes anvils.',
  foundedYear: 2004,
  location: 'Austin, TX, USA',
  timeZone: 'America/Chicago',
  geo: {
    streetAddress: '1 Main St',
    city: 'Austin',
    postalCode: '78701',
    state: 'Texas',
    country: 'United States',
    countryCode: 'US',
    lat: 30.2672,
    lng: -97.7431,
  },
  linkedin: { handle: 'company/acme' },
  twitter: { handle: 'acme' },
  crunchbase: { handle: 'organization/acme' },
  type: 'private',
  phone: '+1 512 555 0100',
  metrics: {
    employees: '51-250',
    employeesCount: 120,
    raised: 12_000_000,
    annualRevenue: 25_000_000,
    estimatedAnnualRevenue: '$10M-$50M',
    trafficRank: 'high',
  },
  tech: ['google_analytics'],
  parent: { domain: 'acme-holdings.com' },
};
