import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardCallViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'call'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    allCallsTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        size: 200,
      },
    }),
    allCallsDirection: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'direction',
        fieldName: 'direction',
        position: 1,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 2,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsMedium: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'medium',
        fieldName: 'medium',
        position: 3,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsStartedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'startedAt',
        fieldName: 'startedAt',
        position: 4,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsDurationInSeconds: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'durationInSeconds',
        fieldName: 'durationInSeconds',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsOwner: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'owner',
        fieldName: 'owner',
        position: 6,
        isVisible: true,
        size: 150,
      },
    }),
    allCallsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'allCalls',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 7,
        isVisible: true,
        size: 150,
      },
    }),
    callRecordPageFieldsTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsDirection: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'direction',
        fieldName: 'direction',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsMedium: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'medium',
        fieldName: 'medium',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsStartedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'startedAt',
        fieldName: 'startedAt',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsAnsweredAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'answeredAt',
        fieldName: 'answeredAt',
        position: 5,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsEndedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'endedAt',
        fieldName: 'endedAt',
        position: 6,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsDurationInSeconds: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'durationInSeconds',
        fieldName: 'durationInSeconds',
        position: 7,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsFromPhoneNumber: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'fromPhoneNumber',
        fieldName: 'fromPhoneNumber',
        position: 8,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsToPhoneNumber: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'toPhoneNumber',
        fieldName: 'toPhoneNumber',
        position: 9,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsOwner: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'owner',
        fieldName: 'owner',
        position: 10,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 11,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsOpportunity: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'opportunity',
        fieldName: 'opportunity',
        position: 12,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsRecordingUrl: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'recordingUrl',
        fieldName: 'recordingUrl',
        position: 13,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsSummary: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'summary',
        fieldName: 'summary',
        position: 14,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    callRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'system',
      },
    }),
    callRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'call',
      context: {
        viewName: 'callRecordPageFields',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'system',
      },
    }),
  };
};
