export enum CallStatus {
  RINGING = 'RINGING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  MISSED = 'MISSED',
  VOICEMAIL = 'VOICEMAIL',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}
