import { MetadataApiClient } from 'twenty-client-sdk/metadata';

// A synced page layout's row id is generated by the server and is NOT the
// universalIdentifier from the manifest, so it has to be looked up at runtime.
export const resolveDashboardPageLayoutId = async (
  universalIdentifier: string,
): Promise<string | null> => {
  const metadataClient = new MetadataApiClient({ runAs: 'application' });

  const { getPageLayouts } = await metadataClient.query({
    getPageLayouts: {
      __args: { pageLayoutType: 'DASHBOARD' },
      id: true,
      universalIdentifier: true,
    },
  });

  const pageLayout = getPageLayouts.find(
    (candidate) => candidate.universalIdentifier === universalIdentifier,
  );

  return pageLayout?.id ?? null;
};
