import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  WHATSAPP_TEMPLATE_CATEGORY_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_COMPONENTS_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_LANGUAGE_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_META_ID_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_PARAMETER_FORMAT_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_QUALITY_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_REJECTED_REASON_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  WHATSAPP_TEMPLATE_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: WHATSAPP_TEMPLATE_UNIVERSAL_IDENTIFIER,
  nameSingular: 'whatsAppTemplate',
  namePlural: 'whatsAppTemplates',
  labelSingular: 'WhatsApp template',
  labelPlural: 'WhatsApp templates',
  description: 'WhatsApp message templates synced from Meta',
  icon: 'IconTemplate',
  labelIdentifierFieldMetadataUniversalIdentifier:
    WHATSAPP_TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: WHATSAPP_TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Template name used when sending',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_META_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'metaTemplateId',
      label: 'Meta template ID',
      description: 'Template ID assigned by Meta',
      icon: 'IconHash',
      isUnique: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_LANGUAGE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'language',
      label: 'Language',
      description: 'Language code, for example en_US',
      icon: 'IconLanguage',
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_CATEGORY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'category',
      label: 'Category',
      description: 'AUTHENTICATION, MARKETING or UTILITY',
      icon: 'IconCategory',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'status',
      label: 'Status',
      description: 'Review status, only APPROVED templates can be sent',
      icon: 'IconProgress',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_QUALITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'quality',
      label: 'Quality',
      description: 'Quality rating reported by Meta',
      icon: 'IconStar',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_PARAMETER_FORMAT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'parameterFormat',
      label: 'Parameter format',
      description: 'NAMED or POSITIONAL',
      icon: 'IconBraces',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_COMPONENTS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RAW_JSON,
      name: 'components',
      label: 'Components',
      description: 'Template components as returned by Meta',
      icon: 'IconCode',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_TEMPLATE_REJECTED_REASON_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'rejectedReason',
      label: 'Rejected reason',
      description: 'Reason given by Meta when a template is rejected',
      icon: 'IconAlertTriangle',
      isNullable: true,
    },
  ],
});
