import { type SelectOptionMeta } from 'src/logic-functions/types/select-option-meta';

export const JOB_FUNCTION_OPTIONS: readonly SelectOptionMeta[] = [
  { key: 'sales', value: 'SALES', label: 'Sales', color: 'green', position: 0 },
  {
    key: 'marketing',
    value: 'MARKETING',
    label: 'Marketing',
    color: 'pink',
    position: 1,
  },
  {
    key: 'finance',
    value: 'FINANCE',
    label: 'Finance',
    color: 'jade',
    position: 2,
  },
  {
    key: 'humanResources',
    value: 'HUMAN_RESOURCES',
    label: 'Human Resources',
    color: 'orange',
    position: 3,
  },
  {
    key: 'informationTechnology',
    value: 'INFORMATION_TECHNOLOGY',
    label: 'Information Technology',
    color: 'blue',
    position: 4,
  },
  {
    key: 'engineering',
    value: 'ENGINEERING',
    label: 'Engineering',
    color: 'sky',
    position: 5,
  },
  {
    key: 'operations',
    value: 'OPERATIONS',
    label: 'Operations',
    color: 'turquoise',
    position: 6,
  },
  {
    key: 'legal',
    value: 'LEGAL',
    label: 'Legal',
    color: 'bronze',
    position: 7,
  },
  {
    key: 'consulting',
    value: 'CONSULTING',
    label: 'Consulting',
    color: 'brown',
    position: 8,
  },
  {
    key: 'customerService',
    value: 'CUSTOMER_SERVICE',
    label: 'Customer Service',
    color: 'amber',
    position: 9,
  },
  {
    key: 'productManagement',
    value: 'PRODUCT_MANAGEMENT',
    label: 'Product Management',
    color: 'violet',
    position: 10,
  },
  {
    key: 'researchDevelopment',
    value: 'RESEARCH_DEVELOPMENT',
    label: 'Research & Development',
    color: 'purple',
    position: 11,
  },
  {
    key: 'administrative',
    value: 'ADMINISTRATIVE',
    label: 'Administrative',
    color: 'gray',
    position: 12,
  },
  {
    key: 'procurement',
    value: 'PROCUREMENT',
    label: 'Procurement',
    color: 'gold',
    position: 13,
  },
  {
    key: 'education',
    value: 'EDUCATION',
    label: 'Education',
    color: 'cyan',
    position: 14,
  },
  {
    key: 'healthcare',
    value: 'HEALTHCARE',
    label: 'Healthcare',
    color: 'crimson',
    position: 15,
  },
  {
    key: 'design',
    value: 'DESIGN',
    label: 'Design',
    color: 'plum',
    position: 16,
  },
  {
    key: 'publicRelations',
    value: 'PUBLIC_RELATIONS',
    label: 'Public Relations',
    color: 'tomato',
    position: 17,
  },
  {
    key: 'qualityAssurance',
    value: 'QUALITY_ASSURANCE',
    label: 'Quality Assurance',
    color: 'mint',
    position: 18,
  },
  {
    key: 'security',
    value: 'SECURITY',
    label: 'Security',
    color: 'red',
    position: 19,
  },
  {
    key: 'realEstate',
    value: 'REAL_ESTATE',
    label: 'Real Estate',
    color: 'iris',
    position: 20,
  },
  { key: 'media', value: 'MEDIA', label: 'Media', color: 'ruby', position: 21 },
  { key: 'other', value: 'OTHER', label: 'Other', color: 'gray', position: 22 },
];
